### PR TITLE
Remove defaultProps (use default parameters)

### PR DESCRIPTION
**Pull request by koteus**
This fixes React warnings: "Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead."

### CODE REVIEW

**Comment by ImLunaHey** [comment]
@compulim any chance you could review this?

**Comment by compulim** [comment]
Sorry, my real world job is very busy recently. I will take a look at this as soon as I am freed up. 🙇🏻‍♂️

This is a very good move, getting rid of `defaultProps`.

I think @koteus spent some time thinking `BasicScrollToBottomCore.initialScrollBehavior`. This is the part I need to some reading time. Will be great if someone could speed me up on this.

**Comment by koteus** [comment]
Hi @compulim I think you mean the default value "smooth" for `initialScrollBehavior`, I provided it by using javascript default value for object destructuring syntax (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#default_value)

Here is the line:
https://github.com/compulim/react-scroll-to-bottom/blob/2d082ec12cecf9890ea14e93915eb7514e6249c9/packages/component/src/BasicScrollToBottom.js#L39

**Review by ImLunaHey — APPROVED** [review]
LGTM

**Comment by koteus** [comment]
Hi @compulim is there anything I could do to help you review this PR?

**Comment by codeXLinkX** [comment]
thanks for working on this @koteus 🤝

**Comment by ImLunaHey** [comment]
hate to be that person but is there anything holding this back?

@compulim the code looks fine, if you can approve the CI this can be merged and a new release can be cut.

**Comment by koteus** [comment]
Hello 👋  
Support for defaultProps in function components has been officially removed in React 19

https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops

Merging this PR will allow `react-scroll-to-bottom` to support React 19 (unless there are any other deprecated features). Right now React 19 is RC and stable release will probably be announced soon.

**Comment by wong2** [comment]
Really hope this can be merged before React 19 release.

**Comment by koteus** [comment]
I rebased my PR on the latest main and I had to create a new PR because my this one was initiated from the `main` branch. During rebase I pressed "sync" and Github closed this PR, so please check out the new one https://github.com/compulim/react-scroll-to-bottom/pull/141

**Comment by 2-fly-4-ai** [comment]
This is still an issue.

**Comment by dimeloper** [comment]
any updates here?

**Comment by josheverett** [comment]
@2-fly-4-ai @dimeloper 

You can use this patch: https://github.com/compulim/react-scroll-to-bottom/pull/141#issuecomment-2325138100

**Comment by koteus** [comment]
Hello, in case you are still looking for a solution, I posted info about my forked version here https://github.com/compulim/react-scroll-to-bottom/pull/141#issuecomment-2773231812

Basically it works with React 19 without warnings, but I rewrote some stuff so there are breaking changes!!

**Pull request closed without merging**
